// Brand palette guard.
//
// The site's theme tokens drifted one step away from the brand palette:
// --color-primary shipped as one hex off Purple, --color-sky one off Cyan, and
// --color-pink a noticeably lighter, cooler pink. Nothing caught it, because
// the palette was copy-pasted into every place that needed it and no copy had
// a relationship to anything checked.
//
// scripts/lib/brand-tokens.js is now the single source: it reads the @theme
// block, and everything that needs a color reads it from there. This suite
// holds that arrangement in place. It keeps no hex literals of its own, so it
// cannot drift from what it guards.

import { execFileSync } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { describe, expect, it } from "vitest";
import {
  BRAND,
  LOGO,
  THEME,
  brandColors,
  logoColors,
  supersededMap,
} from "../scripts/lib/brand-tokens.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");

// The registry names the superseded hexes on purpose, so it would otherwise be
// the first offender of the ban below.
const REGISTRY = "scripts/lib/brand-tokens.js";

// fallback-articles.json carries external LinkedIn copy verbatim and is
// regenerated by `npm run update-fallback`.
const EXEMPT = new Set(["assets/data/fallback-articles.json"]);
const BINARY =
  /\.(png|jpe?g|gif|webp|avif|ico|svgz|woff2?|ttf|otf|eot|pdf|zip|gz|mp4|webm|mp3)$/i;

// Tracked and untracked files both, so a file an agent just wrote is caught
// before it is staged.
function sourceFiles() {
  return execFileSync(
    "git",
    ["ls-files", "-z", "--cached", "--others", "--exclude-standard"],
    { cwd: rootDir, encoding: "utf-8", maxBuffer: 32 * 1024 * 1024 },
  )
    .split("\0")
    .filter(Boolean)
    .filter((file) => !EXEMPT.has(file) && !BINARY.test(file));
}

function scan(files, pattern, onHit) {
  const offenders = [];
  for (const file of files) {
    const abs = path.join(rootDir, file);
    let stat;
    try {
      stat = fs.statSync(abs);
    } catch {
      continue; // deleted between listing and read
    }
    if (!stat.isFile()) continue;

    fs.readFileSync(abs, "utf-8")
      .split("\n")
      .forEach((line, i) => {
        pattern.lastIndex = 0;
        const hit = pattern.exec(line);
        if (hit) offenders.push(onHit(file, i + 1, hit[0]));
      });
  }
  return offenders;
}

describe("Brand palette matches the master logo", () => {
  it("keeps every brand token equal to a color the logo paints with", () => {
    const painted = logoColors();
    const current = brandColors();
    const wrong = BRAND.filter(({ key }) => !painted.has(current[key])).map(
      ({ key, name, token }) =>
        `${token}: ${current[key]} is not in the logo (${name})`,
    );

    expect(
      wrong,
      `${THEME} has drifted from the brand palette in ${LOGO}. The logo is the ` +
        `source of truth, not the guidelines PDF (its printed codes are ` +
        `garbled). Fix the @theme values; do not relax this test. Colors the ` +
        `logo paints with: ${[...painted].sort().join(", ")}`,
    ).toEqual([]);
  });
});

describe("No superseded brand hexes in source", () => {
  it("uses the current brand values everywhere, not the drifted ones", () => {
    const map = supersededMap();
    const pattern = new RegExp(`#(${[...map.keys()].join("|")})\\b`, "gi");
    const files = sourceFiles().filter((file) => file !== REGISTRY);

    const offenders = scan(files, pattern, (file, line, hit) => {
      const target = map.get(hit.slice(1).toLowerCase());
      return `${file}:${line} ${hit} should be ${target.hex} (${target.name})`;
    });

    expect(
      offenders,
      "Superseded brand hexes found. Use the theme token (text-primary, " +
        "bg-pink, ...) where a utility fits, var(--color-*) inside inline SVG, " +
        `and run \`npm run recolor:svgs\` for standalone .svg assets.`,
    ).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// Hard-coded copies of the *current* palette are the mechanism the drift used
// to spread: every literal is a place a future correction has to find by hand.
// Markup and scripts must therefore reference the palette, not restate it.
// ---------------------------------------------------------------------------
describe("Nothing restates the palette", () => {
  const brandPattern = () =>
    new RegExp(
      `#(${Object.values(brandColors())
        .map((hex) => hex.slice(1))
        .join("|")})\\b`,
      "gi",
    );

  it("keeps brand hexes out of hand-edited markup", () => {
    // team/*.html is generated by scripts/generate-team-cards.js, whose
    // template reads the palette. Its theme-color meta needs a real hex
    // because <meta content> cannot resolve var(), and regenerating the cards
    // picks up a palette change on its own.
    const files = sourceFiles().filter(
      (file) => file.endsWith(".html") && !file.startsWith("team/"),
    );

    const offenders = scan(
      files,
      brandPattern(),
      (file, line, hit) => `${file}:${line} ${hit}`,
    );

    expect(
      offenders,
      "Brand hex literals in markup. Use a token utility (text-primary, " +
        "bg-pink, ...) for elements, or var(--color-primary) / var(--color-sky) " +
        "/ var(--color-pink) for inline SVG fill and stroke attributes, so the " +
        "markup follows the palette instead of pinning a copy of it.",
    ).toEqual([]);
  });

  it("keeps brand hexes out of scripts, which must read the palette", () => {
    const files = sourceFiles().filter(
      (file) =>
        file.startsWith("scripts/") &&
        file.endsWith(".js") &&
        file !== REGISTRY,
    );

    const offenders = scan(
      files,
      brandPattern(),
      (file, line, hit) => `${file}:${line} ${hit}`,
    );

    expect(
      offenders,
      `Brand hex literals in scripts. Import the palette from ${REGISTRY} ` +
        "(colors(), brandColors()) so generated output follows a palette " +
        "change without an edit here.",
    ).toEqual([]);
  });
});
