// Brand palette guard.
//
// The site's theme tokens drifted one step away from the brand palette:
// --color-primary shipped as #8d68f6 instead of #8d67f5, --color-sky as
// #13d9e4 instead of #12d9e3, and --color-pink as #fc4bda instead of the
// noticeably lighter/cooler #f74ddd. Nothing caught it, because the theme
// block is just three hex strings with no relationship to anything checked.
//
// The master logo artwork (assets/image/logo.svg) is the source of truth for
// the brand hex codes: the brand guidelines PDF prints three garbled codes,
// the SVG carries the real ones. So this suite reads the colors back out of
// the logo and requires the theme tokens to match them exactly, and it fails
// if any of the superseded values reappears anywhere in source.

import { execFileSync } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { describe, expect, it } from "vitest";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");

const LOGO = "assets/image/logo.svg";
const THEME = "assets/style/input.css";

function read(rel) {
  return fs.readFileSync(path.join(rootDir, rel), "utf-8");
}

// Theme token -> the brand color it must carry, and the value it drifted from.
// `superseded` is what the token used to hold; it is banned from source so a
// copy-paste of the old hex cannot quietly reintroduce the drift.
const BRAND = [
  {
    name: "Purple",
    token: "--color-primary",
    hex: "#8d67f5",
    superseded: "#8d68f6",
  },
  {
    name: "Cyan",
    token: "--color-sky",
    hex: "#12d9e3",
    superseded: "#13d9e4",
  },
  {
    name: "Pink",
    token: "--color-pink",
    hex: "#f74ddd",
    superseded: "#fc4bda",
  },
];

// Every 6-digit hex the logo paints with, lowercased.
function logoColors() {
  const svg = read(LOGO);
  const found = new Set();
  const re = /(?:fill|stroke|stop-color)\s*=\s*"(#[0-9a-fA-F]{6})"/g;
  let m;
  while ((m = re.exec(svg)) !== null) found.add(m[1].toLowerCase());
  return found;
}

// The @theme block only, so a token redefined in a later rule for some local
// override cannot be mistaken for the palette itself.
function themeTokens() {
  const css = read(THEME);
  const block = css.match(/@theme\s*\{([\s\S]*?)\n\}/);
  expect(block, `no @theme block found in ${THEME}`).not.toBeNull();
  const tokens = {};
  const re = /(--color-[a-z0-9-]+)\s*:\s*([^;]+);/gi;
  let m;
  while ((m = re.exec(block[1])) !== null) tokens[m[1]] = m[2].trim();
  return tokens;
}

describe("Brand palette matches the master logo", () => {
  it("finds every brand color in the logo artwork", () => {
    const colors = logoColors();
    const missing = BRAND.filter((c) => !colors.has(c.hex)).map(
      (c) => `${c.name} ${c.hex}`,
    );
    expect(
      missing,
      `${LOGO} no longer paints with these brand colors. If the brand really ` +
        `changed, update BRAND in this file and the tokens in ${THEME} together; ` +
        `the logo is the source of truth, not the guidelines PDF (its printed ` +
        `codes are garbled). Colors found: ${[...colors].sort().join(", ")}`,
    ).toEqual([]);
  });

  it("keeps the theme tokens equal to the brand colors", () => {
    const tokens = themeTokens();
    const wrong = [];
    for (const { name, token, hex } of BRAND) {
      const actual = (tokens[token] ?? "").toLowerCase();
      if (actual !== hex) {
        wrong.push(
          `${token}: ${actual || "(missing)"} should be ${hex} (${name})`,
        );
      }
    }
    expect(
      wrong,
      `${THEME} has drifted from the brand palette in ${LOGO}. Fix the @theme ` +
        `values; do not relax this test.`,
    ).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// The old values are banned outright. Tracked and untracked files are both
// listed (`git ls-files --cached --others`), so a file an agent just wrote is
// caught before it is staged.
// ---------------------------------------------------------------------------
describe("No superseded brand hexes in source", () => {
  // fallback-articles.json carries external LinkedIn copy verbatim and is
  // regenerated by `npm run update-fallback`.
  const EXEMPT = new Set(["assets/data/fallback-articles.json"]);
  const BINARY =
    /\.(png|jpe?g|gif|webp|avif|ico|svgz|woff2?|ttf|otf|eot|pdf|zip|gz|mp4|webm|mp3)$/i;

  it("uses the brand values everywhere, not the drifted ones", () => {
    const files = execFileSync(
      "git",
      ["ls-files", "-z", "--cached", "--others", "--exclude-standard"],
      { cwd: rootDir, encoding: "utf-8", maxBuffer: 32 * 1024 * 1024 },
    )
      .split("\0")
      .filter(Boolean)
      .filter((file) => !EXEMPT.has(file) && !BINARY.test(file));

    // This test file names the old hexes on purpose; it would otherwise be
    // its own first offender.
    const SELF = "tests/brand-colors.test.js";
    const re = new RegExp(
      BRAND.map((c) => c.superseded.slice(1)).join("|"),
      "gi",
    );
    const replacement = new Map(
      BRAND.map((c) => [c.superseded.slice(1), `${c.hex} (${c.name})`]),
    );

    const offenders = [];
    for (const file of files) {
      if (file === SELF) continue;
      const abs = path.join(rootDir, file);
      let stat;
      try {
        stat = fs.statSync(abs);
      } catch {
        continue; // deleted between listing and read
      }
      if (!stat.isFile()) continue;

      const lines = fs.readFileSync(abs, "utf-8").split("\n");
      lines.forEach((line, i) => {
        re.lastIndex = 0;
        const hit = re.exec(line);
        if (hit) {
          const old = hit[0].toLowerCase();
          offenders.push(
            `${file}:${i + 1} #${hit[0]} should be ${replacement.get(old)}`,
          );
        }
      });
    }

    expect(
      offenders,
      "Drifted brand hexes found. Use the theme token (text-primary, " +
        "bg-primary, text-sky, text-pink, ...) where a utility fits, or the " +
        "brand hex from " +
        LOGO +
        " inside SVG markup.",
    ).toEqual([]);
  });
});
